FROM rockylinux/rockylinux:8

LABEL maintainer='Jonas Forsberg'

RUN dnf update -y && \
    dnf install -y sudo systemd python311 findutils  && \
    dnf clean all && \
    rm -rf /var/cache/dnf /var/log/dnf.log

RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -print0 | xargs -0 rm -vf

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT [ "/usr/sbin/init" ]
